[workspace]
resolver = "2"
members = ["projects/crates/*"]

[workspace.package]
version = "0.1.0"
authors = ["Aster <192607617@qq.com>"]
license = "MPL-2.0"
edition = "2021"

[workspace.dependencies]
pandark-types = { path = "projects/crates/pandark-types" }
pandark = { path = "projects/crates/pandark" }
notedown-ir = { git = "https://github.com/notedge/notedown.git", branch = "dev" }
diagnostic = { git = "https://github.com/oovm/diagnostic-rs", branch = "dev", package = "diagnostic", default-features = false, features = ["std", "serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = { version = "2.5", features = ["serde"] }
napi = { version = "2", default-features = false, features = ["napi4"] }
napi-derive = "2"

[profile.release]
lto = true
opt-level = "s"

[workspace.metadata.release]
push = false
tag = false
