[workspace]
resolver = "2"
members = ["projects/crates/*"]

[workspace.package]
version = "0.1.0"
authors = ["Aster <192607617@qq.com>"]
license = "MPL-2.0"
edition = "2021"

[workspace.dependencies]
pandark-types = { path = "projects/crates/pandark-types" }
pandark-fetch = { path = "projects/crates/pandark-fetch" }
pandark-extract = { path = "projects/crates/pandark-extract" }
pandark-store = { path = "projects/crates/pandark-store" }
pandark = { path = "projects/crates/pandark" }
pandark-napi = { path = "projects/crates/pandark-napi" }
notedown-ir = { git = "https://github.com/notedge/notedown.git", branch = "dev" }
diagnostic = { git = "https://github.com/oovm/rust-boost", branch = "dev", package = "diagnostic", default-features = false, features = ["std", "serde"] }
logger = { git = "https://github.com/oovm/rust-boost", branch = "dev", package = "logger" }
fs-tools = { git = "https://github.com/oovm/rust-boost", branch = "dev", package = "fs-tools" }
oak-core = { git = "https://github.com/yggdrasil-language/oaks.git", branch = "dev" }
oak-html = { git = "https://github.com/yggdrasil-language/oaks.git", branch = "dev", package = "oak-html", default-features = false }
yydb = { git = "https://github.com/yy-database/yydb.rs", branch = "dev" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = { version = "2.5", features = ["serde"] }
napi = { version = "2", default-features = false, features = ["napi4"] }
napi-derive = "2"

[profile.release]
lto = true
opt-level = "s"

[workspace.metadata.release]
push = false
tag = false
